Innovate-Inc/EnviroAtlas

widgets/DynamicSymbology/Widget.html
widgets/DynamicSymbology/Widget.js

Added a transparency slider in the dynamic symbology widget.

Add transparency slider to dynamic symbology widget #155

---

widgets/SaveSession/Widget.html
widgets/SaveSession/Widget.js

Seems a bit of a hack but seems to work.

Save user profile session #28

---

widgets/AddWebMapData/Widget.js
widgets/AddWebMapData/config.json

This is an update that allows the popup configuration of the layers from the web map to be added.

Allow a group of layers to be loaded from a web map #202

---

config.json
widgets/DynamicSymbology/Widget.js

Also fixed a bug with the number of classes not being updated.

Fixed so as to save the default renderer for later use

---

widgets/DynamicSymbology/Widget.js

Added definition expression to

Added definintion expression

---

widgets/AddData/nls/strings.js
widgets/AddData/search/AddFromUrlPane.js
widgets/AddData/search/templates/AddFromUrlPane.html

This allows the user to name the layer they are adding.

Added 'Layer Name' Field to AddData widget.

---

widgets/AddData/search/AddFromUrlPane.js
widgets/AddData/search/templates/AddFromUrlPane.html

Allow user to modify layer name if layer is a mapserver or featureserver. I made the textbox for the user to type the layer name into visible if the layer is mapserver or featureserver.

Modified AddData widget Add from Url

---

config.json
widgets/DynamicSymbology/Widget.html
widgets/DynamicSymbology/Widget.js

Added ability to change the color ramp of a layer

Added ability to change color ramp

---

widgets/DynamicSymbology/Widget.js

Fixes issue where clicking the reset button would not reset the color scheme.

Fix the reset of the dynamic symbology tool.

---

config.json
jimu.js/css/jimu-theme.css
themes/TabTheme/widgets/Header/Widget.html
widgets/SimpleSearchFilter/Widget.html
widgets/SimpleSearchFilter/Widget.js
widgets/SimpleSearchFilter/css/style.css

Completed all tasks in 308.  This is an update to any files that were emailed earlier.  GitHub from now on!
Added  a bold line below the header that should be sufficient for the header bar adjustment
Also added line "openAtStart": true to the SimpleSearchFilter in config.json so the panel defautls to open position.

ticket 308 completed

---

widgets/Drawer/Widget.js
widgets/DrawerAddDataTools/Widget.js
widgets/DrawerMappingTools/Widget.js

This will make it so that the draw widget will not automatically close.

Modified drawer widgets to not close on opening containing widgets

---

widgets/BoundaryLayer/Widget.js
widgets/PeopleAndBuildSpaces/Widget.html
widgets/PeopleAndBuildSpaces/Widget.js
widgets/PeopleAndBuildSpaces/css/style.css

Mostly style changes to P&BS.
Added collapsible header and ordered layers alphabetically
Alignment of check-boxes and text in Boundaries

changed style of P&BS to match SimpleSearch

---

widgets/Demo/Widget.js
widgets/Demo/config.json

Fixed so guided tour be run more than once.
Added an end button to the popup dialogs in the guided tour

Fixed the tour widget 

---

config.json
index.html
widgets/Splash/Widget.js
widgets/SynchronizeMap/Widget.js

Cleanup pageload errors

---

jimu.js/main.js

no wonder I couldn't search for "Ecoregions"

update topics - one missing

---

widgets/DynamicSymbology/Widget.js

Reset button on dynamic symbology wigdet now will reset the symbology to that specified in the configs

Changed dynamic symbology widget reset code

---

scripts/SpreadsheettoJSON.py
scripts/SpreadsheettoJSON_ancillary.py
scripts/config.json
scripts/config_BOUNDARY.json
scripts/config_PBS.json
widgets/BoundaryLayer/Widget.js

Update Python script syntax to be compatible with openpyxl 2.4 and above

Config scripts

---

widgets/PeopleAndBuildSpaces/Widget.html
widgets/PeopleAndBuildSpaces/Widget.js
widgets/PeopleAndBuildSpaces/css/style.css
widgets/SimpleSearchFilter/Widget.js
widgets/SimpleSearchFilter/css/style.css

made P&BS a little more like ES&B both in appearance and code.

fix disappering checks and add hide icon button

---

widgets/PeopleAndBuildSpaces/Widget.js

#565 -- An easy one; i'll take it.

Fix hover description for P&BS

---

widgets/BoundaryLayer/Widget.js

565 hover for all three panes now!

Boundary layer hover text
